[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "csv_sorter"
version = "0.2.0"
description = "A small tool to sort CSV files by the second column, and generate random CSV data"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "JIFR", email = "your@email.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "pandas"
]

[project.scripts]
csv-sort    = "csv_sorter.process:main"
csv-generate = "csv_sorter.generate:main"

[project.urls]
Homepage = "https://github.com/ChenLinLinC/csv_sorter"
Issues = "https://github.com/ChenLinLinC/csv_sorter/issues"